version: '2'

services:

  apanaj_optimizer-jpeg:
    build:
      context: ./.docker-compose/optimizer-jpeg
      dockerfile: Dockerfile
    image: apanaj_ptimizer-jpeg
      expose:
      ## On Private Network
        - "80"
    networks:
      - apanaj-network
      - network-front-proxy

networks:
  apanaj-network:
  network-front-proxy:
    external:
      name: frontproxy_front-network
##              ^             ^
##       name of project    network created inside that project
