version: '2'

services:

  apanaj_optimizer-image:
    networks:
      - apanaj-network
      - network-front-proxy

networks:
  apanaj-network:
  network-front-proxy:
    external:
      name: frontproxy_front-network
##              ^             ^
##       name of project    network created inside that project
